version: 0.2
cache:
  paths:
    - '/root/.m2/**/*'
env:
  git-credential-helper: yes
phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - git clone https://github.com/bw-robotics/do-codebuild-common.git
      - |
        echo "Installing yq..."
        wget -qO /usr/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
        chmod +x /usr/bin/yq
        echo "✅ Installed yq... print version"
        yq --version
        echo
  build:
    on-failure: ABORT
    commands:
      - echo Deploying Keycloak Kafka Custom jar...
      - echo $SETTINGS > settings.xml
      - mvn deploy -s settings.xml