version: 0.2
cache:
  paths:
    - '/root/.m2/**/*'
phases:
  install:
    runtime-versions:
      java: corretto21
  build:
    commands:
      - echo Deploying Keycloak Kafka Custom jar...
      - echo $SETTINGS > settings.xml
      - mvn deploy -s settings.xml