name: PR keycloak-kafka-custom

on:
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on:
      # docs: https://docs.aws.amazon.com/codebuild/latest/userguide/sample-github-action-runners-update-yaml.images.html
      - codebuild-compass-backend-${{ github.run_id }}-${{ github.run_attempt }}
        image:aws/codebuild/standard:7.0
        instance-size:small
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Java 21
        uses: actions/setup-java@v5
        with:
          distribution: corretto
          java-version: "21"
          cache: maven

      - name: Write settings.xml
        run: |
          echo "$SETTINGS" > settings.xml

      - name: Maven install
        run: mvn install -s settings.xml
